### ISSUE TITLE
空间回收 的  winsxs组件 出错  系统找不到指定的文件

### ISSUE THREAD

**Issue by wsldb97532** [Chuyu-Team/Dism-Multi-language#103]

**Comment by wsldb97532** [comment]
扫描出来的是C:\Windows\winsxs\amd64_Microsoft-Windows-D..gement-WinProviders_31bf3856ad364e35_10.0.15063.0_none_c86192d0ddbad933\

**Comment by mingkuang-Chuyu** [comment]
建议 抽空远程下，谢谢  我的QQ号是 343183163

**Comment by clfsoft** [comment]
我也有类似问题.(windows7)
结果原因是系统本身损坏了,可以尝试升级安装windows

**Comment by verdy-p** [comment]
I note you sent me an invitation to the multilingual project. However I can
help for French and English, provided you make at least some basic
translation to English, because I have difficulties with Chinese (like many
others).

It would be more productive for your project to provide English (at least a
basic level in a specific internal sublocale such as "en-CN" (that you
don't need to publish in the software but that you'll use internally for
your development), so that a correct plain "en" English can be produced and
other translations (such as French and others) can be made based on that
corrected English.

You would get much more help for your project because many more people can
read English and translate it, than Chinese.

For your emails, please include some basic English: automatic translators
produce very strange "imaged" text from Chinese which is often hard to
decipher.

Thanks


2017-06-13 7:58 GMT+02:00 clf <notifications@github.com>:

**Comment by clfsoft** [comment]
I got similiar error and found my optionalfeatures comand show me a blank page.
I thought something wrong with my system . I have try windows 7 readiness tool but no luck. 
finally fix by reinstall windows 7  in upgrade mode (reserved all apps).

**Comment by mingkuang-Chuyu** [comment]
@verdy-p  Thanks……

**Comment by mingkuang-Chuyu** [comment]
用户并未加我QQ，另外这种问题一般都是精简过度所致。关闭问题
