### ISSUE TITLE
空间回收问题反馈

### ISSUE THREAD

**Issue by ldqk** [Chuyu-Team/Dism-Multi-language#128]
笔记本上使用dism++进行空间回收后，导致了显示屏亮度不能调了，望检查和修复，测试机型：华硕n550，ThinkPad T440

**Comment by mingkuang-Chuyu** [comment]
Hi，你有没有使用过期驱动清理？或者禁用了什么开机启动项或者服务。

你的问题可能是驱动被删了，或者相关启动项被禁用了

**Comment by ldqk** [comment]
我觉得应该是过期驱动清理的问题

**Comment by mingkuang-Chuyu** [comment]
过期驱动一定可能会出现误杀，因此这个项目是风险项目。目前也暂时没有好的办法知道驱动是否真的在使用……

建议你暂时重新安装显示屏亮度控制驱动。并且不要使用驱动清理，谢谢，如果确实存在较多不需要的驱动，可以在驱动管理中 手动删除 不需要的驱动。


抱歉，给你造成了困扰

**Comment by mingkuang-Chuyu** [comment]
要不提供下驱动名称，我写个过滤规则？

**Comment by mingkuang-Chuyu** [comment]
驱动管理，可以查看驱动名称，然后提供下误杀的驱动名称，然后我添加到过滤列表，

**Comment by mingkuang-Chuyu** [comment]
或者点击驱动管理，扫描下。右侧会显示即将删除的驱动。

**Comment by suwakowww** [comment]
记得当时装驱动的时候装完核显驱动之后就能调亮度了，不知道是不是这个，因为现在笔记本（特别是sandy bridge/ix-2xxx系列开始）基本用的核显做输出，独显基本用来加速。
另外这两个型号的机器好像都是haswell（ix-4xxx）系列的cpu。
(maybe the haswell series graphics driver is cleaned by mistake, because the notebook (since sandy bridge series) is output from ia cores, and cleaned this can cause the brightness can't be change)

**Comment by mingkuang-Chuyu** [comment]
长时间无回复，暂时关闭
