### ISSUE TITLE
Removing languages not needed

### ISSUE THREAD

**Issue by jtan2000** [Chuyu-Team/Dism-Multi-language#145]
I got an windows 7 ultimate iso with zh-cn and zh-tw lp.cab slipstream into install.wim. 

How can I remove those using Dism++  and create a new install.wim ?

**Comment by verdy-p** [comment]
Yes it is easy to do that, just use DISM++ to mount the WIM image into a new empty directory (if this is an ESD, you'll need first to convert it to a WIM, which takes mere space than ESD which is more compressed)
Then use DISM++ UI to manage packages you want to remove or integrate (including drivers or other applications if needed, as well as Windows Updates that can also be downloaded and applied in it with DISM++; you may want also to perform some cleanup to remvoe older versions before updates were applied as they are still in the mounted image: Windows default images are full of old crap that takes considerable space: on a live Windows system with several Windwos Updates or new versions installed, it frequently keeps tens of gigabytes for these craps, including system snapshots that you won't need once you've decided to keep a version).
Then dismount the WIM from its folder (also from DISM++). Use that new WIM image to install your new system, or to create an updated ESD also with DISM++ (which is more compact: you may need it if you have a small USB Flash key)
Note: it's highly preferable to install any Windows image from a USB Flash disk, rather than burning a DVD(RW): it is considerably faster and even more reliable.

**Comment by verdy-p** [comment]
Note: removing languages (MUI or LUI packages) from windows does not mean they won't be available at all: they will be installable on demand from the normal UI and downloaded from Windows Update.
Note also that some languages are partial translations (LUI), requiring a base MUI package to work.
Full MUI languages (that don't depend on other translation packages) include major languages: English, French, Spanish, Chinese, Japanese, Russian, Portuguese, German, Italian, and a few others. Many other supported languages are LUI depending on these: if you select one of them, the base MUI languages they depend on will also be installed.

**Comment by jtan2000** [comment]
Thank you verdy-p for your detail instructions. 

The only part I still cannot do is to remove those two languages using DISM++.

I mounted my win7 ultimate.iso   install.wim.  
use disk clean to cleanup
drivers to add usb3 
updates to add whatever update necessary
and when I click region & language section it has  en-US, zh-cn and zh-tw.

so how can I remove the zh-cn and zh-tw from the image (install.wim) ?

I do not see a delete command perhaps your can further guide me on this.   Thank you.

**Comment by mingkuang-Chuyu** [comment]
Please give me Error Message when you remove language packages. Thanks

**Comment by verdy-p** [comment]
These are listed within the "Optional components", just below the
"Parameters", "Drivers", and "Features".

Note: do NOT uninstall some "optional components" that have a size
displayed as "0": they are actually required.

For example "Fix for KB2839636" is related to languages packs in Windows
10. Microsoft describes it as meant for Windows 7 or 8, but actually it is
a necessary pack: trying to remove it, your PC won't be able to reboot,
because it is not stored in normal Windows partition but in the small
hidden UEFI partition (FAT32 formatted). If you remove this pack, UEFI boot
will fail immediately and you won't even be able to enter your BIOS if it
was set to use the "Fast Boot" and "Windows 8/10 secure mode": the BIOS
directly tries to launch the UEFI application, that will fail immediately
and reboot in an infinite loop. And you won't be abel to reboot from any
other device.

If you do it, the only way to restore an access to the BIOS, disable
FastBoot, and secure mode and select another boot device (USB Flash disk,
DVD, other partition) or boot method (non-UEFI) will be to **physically**
unplug the hard disk or SSD (the data cable) where UEFI was detected and
lauchned immediately by the BIOS. and then make necessary BIOS settings
changed to allow booting another way.

And then you'll need to reinstall Windows after remounting the cable (the
simple restoration does not work, as it will not restore the content of the
UEFI partition). To restore the PC bootability, you'll need to be able to
boot on a USB Flash disk or DVD containing a Windows 8 or 10 image, to fix
the boot (you actually don't need to reinstall Windows or your apps, all
your data is still there).

Windows 8/10 installers also have severe troubles handling the "BCD STORE"
where each new installation adds bogous entries that are not removed. The
Windows restoration tools at boot time also fail to interpret these fake
BCD entries, and may incorrectly reassign the drive letters or remount
undesired disk volumes.

Note also that the current method by which DISM++ tries to install itselfs
as a boot application (in UEFI) also fails: the BCD store is also
incorrectly set and DISM++ no longer works as a "os loader application
working in WinRE mode. Windows installers also fail constantly restoring
the winRE environment, except after a COMPLETE reinstallation (overwirting
all past versions and removing existing apps, and all the contents of the
registry).

It's unbelievable that Windows does not provide an easy way to restore the
WinRE environment ("ReAgentc.exe" is definitely bogous, it actually does
nothing, and does not even attempts to locate the needed files from Wincows
Update servers). The winRE environment is only installed once from the
initial installation medium (and then never updated even if there's a known
vulnerability in it...)

Some antivirus solutions provide a way to restore a working WinRE
environment in its partition the initial installation was made in the
C:\Recovery partition, then later after first boot, Reagentc.exe moved it
on its own partition (deleted from C:\ where it just remains a small XML
file indicating where the recovery software should be now) where it cannot
be restored. Restoring it from the windows installation medium is a real
nightmare with extremely tricky commands to fix drives, set some registry
values, and set correct permissions for the "secure boot mode". Normally
the recovery should be in its own small NTFS partition hidden at end of the
boot drive.

The recovery environemnt also has its own "locale" requirements needing the
"fix" I gave above. Here we are in a strange gray area that Microsoft does
not correctly document, and only supported by broken Microsoft tools used
normally only during the first installation but never tested to be used to
restore a working system. When Microsoft says that windwos 10 should be
able to repair itself, it is wrong: the Recovery environement (in its small
hidden NTFS partition) or the UEFI (FAT32) partition (which also contains
the BCD store data) are NEVER repaired by Windows, but frequently danaged
or filled with spurious data by Microsoft's own installers.

2017-07-19 17:11 GMT+02:00 jtan2000 <notifications@github.com>:

**Comment by jtan2000** [comment]
![pic](https://user-images.githubusercontent.com/30292790/28379632-3c5ca18e-6c69-11e7-8a7e-a11582a1b5a3.png)

I am lost ... I still do not understand how to remove them.

**Comment by mingkuang-Chuyu** [comment]
Please Check    Updates   --->  Installed Updates

Then remove your languages.

**Comment by jtan2000** [comment]
Thank you !
