### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#178]
I was wondering if you can create "another project", to create a tool that updates "Microsoft Office" in the style of Dism ++, obviously collaborate with the translation.

It's just a suggestion.

**Comment by mingkuang-Chuyu** [comment]
I'm sorry. There is no plan at the moment...

**Comment by Jhovany200** [comment]
ok

**Comment by verdy-p** [comment]
For now you can use "Hard Links" compression (slow), which locates files with exactly the same contents (including all data streams), security attributes, but only found under distinct files names or in multiple folders). Note that this may also locate duplicate directories (that index the same files), but their use on Windows is rare compared to the many hardlinks created in the Component Store (in WinSxS) by component installers and then hardlinked to their final installation target (without duplicating the content, but under a different path and possibly a different filename).
Hard links may also created for virtualized directories, but there are most often implemented as reparse points (soft links living in memory from an empty directory mount point)
Windows uses lots of these technics to compact its storage needs without duplicating everything. But as the detection of new files with the same contents as other existing files on the same volume requires hashing the content, if the content is modified, this is not possible to do that in live mode.

Note also that two files with identical contents may have different attributes (different owner, different access rights, if if two distinct security contexts allow modifications, and they are not coordinated, this could cause unexpected damages if their content was shared; windows still allows this using virtualized file histories where each one will have their own versioned contents but may still share the same unmodified parts)

As a result, the traditional way of finding duplicating files by content generally fails, except for basic documents, but should not be used if files are executables or scripts: you could delete required files for an app, if you remove one copy, or replace them by hardlinks but not preserving their distinct attributes.

This is not specific to Windows: you have similar problems on Linux: deduplicating files requires user control and analysis of how files are used by apps. You'll want to dedup only media files (music, images, videos), office documents, but not source files (you may want to preserve backups without having to look at which files were modified since the archiving, but for this reason, backups should be done to a distinct storage volume

If backups they are on the same volume, NTFS provides a simpler and more efficient way, using versioned "snapshots" on volumes where you've enabled the detection of changes with "shadow" copies: shadow copies are also working like hardlinks but they are dynamic, no copy is actually done immediately, only modifications are made in separate sectors, preserving the former version completely intact kept in the snapshot which also keeps the unmodified clusters shared by the modifed versions).

Note the VSS (shodwo copies) are not available on FAT32/xFAT volumes, where only "file histories" are kept (they require copying the full content of the file, like classic backups)
