### ISSUE TITLE
Suggestions and bug reports regarding Dism++

### ISSUE THREAD

**Issue by Zero3K** [Chuyu-Team/Dism-Multi-language#203]
1. There should be the ability to run the Disk Clean function via a command line option (where it cleans the items checked in that section) such as /clean.
2. The Update Checking function of it didn't detect the updates that Windows Update showed me (I am using it under Windows 7 SP1).
3. The ability to delete drivers is missing from the Drivers section.
4. There were some errors when doing the Disk Clean. I am attaching the log file (which should show the errors in English if the user is running that language as their OS).
5. It should apply the "Explorer restart required" options shown in the "System Optimizer" section without actually needing to restart it. So that way the user can restart it at his/her's convenience.

[Dism++.zip](https://github.com/Chuyu-Team/Dism-Multi-language/files/1254566/Dism.zip)

**Comment by mingkuang-Chuyu** [comment]
Hi, Thanks for your help.

1.There should be the ability to run the Disk Clean function via a command line option (where it cleans the items checked in that section) such as /clean.
Thank you for your comments later on.

2.The Update Checking function of it didn't detect the updates that Windows Update showed me (I am using it under Windows 7 SP1).
Because Your OS need restart.
Logs : 2017-08-26 16:04:52, Error	PID=3824 TID=5732, XXXXXXXXX   0x800F0806

3.The ability to delete drivers is missing from the Drivers section.
you need enable "Expert mode", otherwise you'll not see some risk function.

4.There were some errors when doing the Disk Clean. I am attaching the log file (which should show the errors in English if the user is running that language as their OS).
This is not considered temporarily. In addition, the log of other programs is also only their mother tongue.

5.It should apply the "Explorer restart required" options shown in the "System Optimizer" section without actually needing to restart it. So that way the user can restart it at his/her's convenience.
This proposal is really good, reduce the interference to the user. But do not know how to show to the users.
