### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#227]
How can I copy the downloaded updates?, and how can I apply them to another computer so that I do not re-download the updates.

so you understand me better just want updates and implement them on another computer.

Attention: I don't want to integrate in the Windows iso, only the updates to put them in another computer.

Thanks

**Comment by mingkuang-Chuyu** [comment]
Hi, you can copy “Config/UpdateCache” in Didm++ root path.

获取 Outlook for Android<https://aka.ms/ghei36>


发件人: Jhovany200
发送时间: 9月22日星期五 12:42
主题: [Chuyu-Team/Dism-Multi-language] Question (#227)
收件人: Chuyu-Team/Dism-Multi-language
抄送: Subscribed

How can I copy the downloaded updates?, and how can I apply them to another computer so that I do not re-download the updates.

so you understand me better just want updates and implement them on another computer.

Attention: I don't want to integrate in the Windows iso, only the updates to put them in another computer.

―

**Comment by Jhovany200** [comment]
Thanks for your reply.
