### ISSUE TITLE
提交规则：关闭WfpDiag.ETL日志

### ISSUE THREAD

**Issue by powerxing04** [Chuyu-Team/Dism-Multi-language#281]
命令行方式：
NETSH WFP SET OPTIONS NETEVENTS = OFF

注册表方式：
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\BFE\Parameters\Policy\Options]
"CollectNetEvents"=dword:00000000

**Comment by mingkuang-Chuyu** [comment]
谢谢支持~~

**Comment by mingkuang-Chuyu** [comment]
谢谢支持，id：0fa08da1已经添加此规则

**Comment by verdy-p** [comment]
When adding new options like this in Dism++, please make sure that there's not just a Chinese text for the UI, but add at least a rough English translation (even if it gets corrected later by native English translators).

Please don't just push it in updates sent to everyone, most of your users CANNOT read Chinese at all and cannot interpret this Chinese "garbage" in their translated UI (and there's also still no way to copy these texts in the UI to the clipboard to find some rough translation online) ! Thanks.

Instead take the time to copy-paste the text and use at least some online translator to English, and push it at least in the English language XML bundle (with a dummy q="" attribute to mark it as fuzzy, so transaltors will easily spot these new additions, because there's no way to locate the Chinese text hidden in submitted patches in the opensourced folder, also because you do not add any readable version history in Dism updates, and do not even list them with their Github issue number which would facilitate locating where these new/modified texts were submitted)

**Comment by verdy-p** [comment]
So in summary,

This is a trace file created by Windows to collect diagnostics information around ipsec and firewall activity.

Such info could be later read by a troubleshooting tool to help diagnose connectivity failures. I would not expect it to be active unless you are receiving (or maybe sending) traffic which is being blocked by your security software.

The builtin firewall may collect these events in large files which may sometimes become very large, and the option here is supposed to stop this collection when the user is unable to analyse them and does not intend to submit these logs to a professional. These ETL log from the firewall are normally small, and can already be cleared with the Windows Events Viewer. But they can also be disabled in the Windows Event viewer interface itself, which provides a summary of events by source. In some cases, the log files may exhaust their maximum size and Windows will either start recyling them by dropping the oldest messages to keep only the most recent ones (so no maintenance is needed in this case), or will stop logging more events (you'll get an additional event in the separate system log saying that the event log file from the firewall is full and needs either archiving for later inspection, and cleanup before Windows can keep new loged events, or that it needs to be tuned to give it a larger maximum size).

It you have a properly concigured Internet router, it should already block most unwanted incoming traffic and the internal firewall will block very few messages, except if your PC is being harnessed by some malicious third party: when this log file fills too fast, you should inspect your security settings and system/software updates, and inspect network activities to detect unwanted apps/components, and run an antivirus/antispyware/antirootkit scan (and probably you should also consider rebooting Windows to stop some background processes that are constantly failing and generate lot of logs: these apps may need to be reset or may have their own logs).
