### ISSUE TITLE
Dism++某些优化项会消失问题

### ISSUE THREAD

**Issue by masktao** [Chuyu-Team/Dism-Multi-language#283]
系统调整的软件,只用过dism++. 发现spotlight无法使用,选择后锁屏,再登录发现聚焦没有被选择,失效了
我收到一个答案
![image](https://user-images.githubusercontent.com/13614353/32409189-248f7d6e-c1e2-11e7-9a8f-914751e4831c.png)

平时只用dism++清理系统,但不知道是否把聚焦功能清理了?

**Comment by mingkuang-Chuyu** [comment]
Dism++有个系统优化规则，叫 关闭Windows 10推广。

这个设置会移除所有Windows 10里面的推广行为。

你应该是启用了这个设置，重新关闭，然后重启Windows 10即可。

**Comment by masktao** [comment]
如你所说,我去找了下,只找到关闭一个商店的推广,而且关闭之后,重启电脑,再打开发现dism,发现这个选项都没有了.天啊,这个选项消失了
![image](https://user-images.githubusercontent.com/13614353/32526653-8105960c-c465-11e7-889f-d3174070d657.png)

**Comment by mingkuang-Chuyu** [comment]
谢谢反馈，我检测了规则。确实会这样不显示。看来你确实关闭了锁屏聚焦推广。

暂时可以这样重新打开

打开注册表

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager]

然后创建一个注册表 RotatingLockScreenEnable=1（REG_DWORD）

或者等待我今天发布新的规则库。

**Comment by mingkuang-Chuyu** [comment]
ID 649b4432,已经修正规则检测逻辑。请耐心等候推送

**Comment by mingkuang-Chuyu** [comment]
HI,规则更新已经推送。请查收

**Comment by verdy-p** [comment]
**Windows 10 focus failure is not caused by Dism?** (rough translation)
**Dism++ some optimization problems will disappear** (new title)

System adjustment software, only used Dism++. Found spotlight can not be used, select the lock screen, then log in to find that the focus has not been selected, lapsed.
I received an answer (see image).

> Dism ++ has a system optimization rules, called the closure of Windows 10 promotion.
> 
> This setting will remove all Windows 10 promotion activities.
> 
> You should enable this setting, you turn off this optimization, so the system will re-display the promotion. This setting may need to restart Windows 10 to work.

As you said, I went to find the next, only to find a promotion to close a store, and shut down, restart the computer, and then open the DISM, found that this option is gone. God, this option disappeared. (see image)

> Thanks for the feedback, I checked the rules. This does not show up. It seems that you did close the lock screen focused promotion.
> Temporarily can be reopened this way:
> * Open the registry key
>  [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager]
> * Then create a registry value: RotatingLockScreenEnable = 1 (REG_DWORD)
> 
> Or wait for me to release a new rule base today.
