### ISSUE TITLE
关于补丁更新的bug

### ISSUE THREAD

**Issue by zlx42** [Chuyu-Team/Dism-Multi-language#285]
我这边一直提示有一个office补丁KB3191931，问题是机器自己检查升级找不到，用DISM++能查到更新但是安装不上，点详细信息结果微软网页上显示该页面不存在，百度搜索不到，谷歌（翻墙），bing也搜索不到，我记得最开始的时候是搜索到是8月的安全更新，但是现在没了，问题是dism++还一直能扫描到，建议添加一个屏蔽补丁的功能。

**Comment by mingkuang-Chuyu** [comment]
Hi，请问能否加QQ好友？ 343183163 谢谢

**Comment by verdy-p** [comment]
**Bug on patch update**

My side has been prompted to have an office patch KB3191931. The problem is that the machine can not find their own inspection upgrade: Dism++ can be found updated but not installed, the results of details on Microsoft Web page shows that the page does not exist, Baidu search, Google (over the wall), Bing also not search. I remember the beginning of the search is a security update in August, but now gone. The problem is that Dism++ has been able to scan, it is recommended to add a shield patch feature.

**Comment by asmosn** [comment]
经常更新失败
