### ISSUE TITLE
Window 10 部署后Sysprep阶段没有画面

### ISSUE THREAD

**Issue by scccboom** [Chuyu-Team/Dism-Multi-language#286]
1. 有2块硬盘都使用（EFI+GPT），第1块硬盘已安装win10 1709 x64。
2. 在1硬盘系统中使用dism++向第2块硬盘释放wim(安装过更新)，释放选项都是默认的。
3. 开机后进入Sysprep阶段能听到“小娜”的声音，看不到画面。
    - 使用系统自带dism释放wim无此现象。
4. 使用讲述人配置成功后可以进入系统。

**Comment by mingkuang-Chuyu** [comment]
感谢 反馈~

话说 释放的WIM 是否是同一个？也就是Dism++释放的WIM跟Dism释放的WIM文件是否是同一个？

**Comment by scccboom** [comment]
今天我又装了一便，发现不是软件的问题-_-!。是因为我有一块硬盘是ssd，释放到ssd上的系统就会没有画面。释放到机械硬盘上的系统就没有问题。

**Comment by verdy-p** [comment]
There is no screen in Sysprep stage after Window 10 deployment
==========================================

1. There are two hard drives (EFI + GPT), the first one has win10 1709 x64 installed.

2. In a hard disk system, using Dism++ released to the second hard disk Wim (installed updated), the release options are the default.

3. After boot into the Sysprep stage can hear "Xiaona" sound, do not see the picture.

  * Use the system comes with dism release wim no such phenomenon.

4. After using the Narrator configured successfully enter the system.

-----

Today, I installed again and found that the problem is not software -_- !. Because I have a hard drive is SSD, released to SSD on the system there will be no picture. There is no problem with the system that is released to the mechanical hard disk.

**Comment by mingkuang-Chuyu** [comment]
谢谢，最后发现问题就好。怪不得问题怎么那么诡异。

感谢支持
