### ISSUE TITLE
选项 语言 韩文 问题

### ISSUE THREAD

**Issue by DevilsJINJIN** [Chuyu-Team/Dism-Multi-language#287]
系统下打开Dism选择韩文没有问题正常显示 但是选择系统还原-格式化 重启进入Dism韩文选项全部显示方框乱码 别的语言都没有问题日语也没有问题 只有韩文有这问题 本来推荐给韩国的朋友用 结果系统下可以正常显示 选择格式化还原重启就是乱码了 希望尽快解决

**Comment by verdy-p** [comment]
**Korean language option question**
Dism under the system to choose Korean no problem. Normal display, but select System Restore - Formatted, Reboot into Dism, Korean Options Show. All Frames are garbled. Other languages are no problem. Japanese is no problem. Korean only.
This problem was originally recommended to Korean friends with the results: the system can normally display the format. Selection Restarting is garbled. Hope that there's solution as soon as possible.

**Comment by mingkuang-Chuyu** [comment]
Hi, 这个是系统本身的问题。因为他的RE没有韩语字体，这导致Dism++无法显示韩文。

我猜测 他的系统之前 不是正规的韩语系统，而是通过安装韩语语言包 搞过来的。这就导致系统里面的RE没有 韩语相关字体。 此问题只能靠他自己解决，就是给RE系统添加韩语语言包……
