### ISSUE TITLE
could dism++ add /Cleanup-Image function?

### ISSUE THREAD

**Issue by KevinDaiVIP** [Chuyu-Team/Dism-Multi-language#296]
I always use the following command.
DISM /online /Cleanup-Image /StartComponentCleanup /ResetBase

Now, very time, must close Dism++ first and run the command in cmd window.
Then re-open Dism++ to do further processes.
 Could you consider to add /Cleanup-Image, /StartComponentCleanup, /ResetBase function? 
Thank you very much.

**Comment by verdy-p** [comment]
Cleanup image is already performed by DISM (this is waht gives you over 15GB of backups or previous components to be cleaned after each installation of a new Windows 10 build, and this is not just for "Windows.old", but really within the new installation as these components were initially kept before staring a version migration after first boot). In DISM this is done with options related to the Component Store (winSxS).
Note that "StartComponentCleanup" may cause some problems with the impossibility to uninstall system patches (you'll have to wait then for a newer version of affected components from Windows Update) or some programs uininstallers will fail to revert a component to a backward version that was kept in archive, but was from the standard release branch, instead of a QFE fix from Microsoft which is not always supported by Microsoft but made for specific applications.
I tried /Cleanup-Image, /StartComponentCleanup after performing all DISM++ cleanups and this does not save so much storage (a few megabytes, mostly within temporary folders and in DISM.log or CBS.log, but this operation also adds some used storage for new logs, so there's actually no benefit at all).
It's just simpler to run again the cleanup in DISM++ after a second boot (once component migration has been done, as well as when the user's preferences have been migrated) to clean about 1-2GB

**Comment by verdy-p** [comment]
Also "ResetBase is dangereous": it could disconnect your existing installation from a know stable branch from which a Windows build version upgrade is possible.

**Comment by mingkuang-Chuyu** [comment]
Dism++ support this function.
In Dism ++ it's called Replaced WinSxS assemblies.
By the way, this feature is supported only by Dism++, MS Dism ignores the ResetBase parameter in Windows 10.
