### ISSUE TITLE
Add clean rules "$Windows.~BT" and "$Windows.~WS"

### ISSUE THREAD

**Issue by Jhovany200** [Chuyu-Team/Dism-Multi-language#375]
I could add the option to clean "$Windows.~BT" and "$Windows.~WS" or join it with "Windows.old" cleaning.
It is usually deleted automatically, but on some computers for unknown reasons they are not deleted. "And it would be good if you added it".

**Comment by verdy-p** [comment]
These are not deleted if for any reason an installation/upgrade fails and is reverted back because they still contain logs of what happened and files that were attempted to install are keeping their state to allow diagnostising them.
If you reattempt the installation of any Windows image by Windows Update after the failed boot to the new image that was reverted, once you restart the update, the first phase of Windows Update will automatically clean them all to download again a new copy of the image, extract files there, and create new logs for the next boot try.
So instead of retrying the installation, you may want to keep these for diagnostic and it may take some long time to investigate and receive replies if you ask some support. The update will normally not be reattempted (at least not immediately) because it would prevent this diagnostic.
But you may want to diagnostic these yourself, and then decide not to update now, wait for another new Windows version image, but continue with your existing version by erasing completely the failed installer files and its logs: Windows itself allows doing that with it's own "CLEANMGR" tool (which is much slower than Dism++, but performs the same thing)
Trying to remove these two folders manually with the Explorer is not so easy (you may get permission denied, even when you're logged in as the local administrator, some files may still be locked by background tools analyzing them or reporting them to Microsoft for analysis of failures, or sometimes because some files are hardlinked to the same files as the currently running installation, and the windows Explorer is not able to check that the deletion of the same file referenced in another directory is still safe and won't alter the other references to the same files stored in other folders; in some cases you may have some of these files from the installer active at their new path, because they were loaded by Windows from there from the search path, instead of the normal path where they were supposed to be loaded and locked; you need a tool to delink files safely before trying to remove one copy: if deletion fails, remove the other copy and move the remaining copy into the old location, but this is quite tricky to do and safer to do by cleanup at boot time without many processes running concurrently and potentially locking many files and needing them frequently)

**Comment by Jhovany200** [comment]
He said if they can add these cleaning parameters to Dism++ (for expert or inexperienced users) and thus have them in the same tool that is Dism++. And thus save free space when cleaning them.
Well, it's just a suggestion.
