### ISSUE TITLE
(Where) Can I get the source code of Dism++ ? 

### ISSUE THREAD

**Issue by mercury233** [Chuyu-Team/Dism-Multi-language#548]
It is said _开源是一种美德，也是一种实力的象征_, but I didn't see the source code of Dism++ in the GitHub of Chuyu-Team.

**Comment by mingkuang-Chuyu** [comment]
We open source is the Dism++ base library, For example VC-LTL, CppHelper, YY-Thunks, etc.

Just like Microsoft's official github open source Windows OS source code?

**Comment by MouriNaruto** [comment]
@mercury233 You are a Chinese. I think you should use Chinese to open an issue in this repository.

**Comment by mercury233** [comment]
@MouriNaruto Sorry, I thought it is not only Chinese who are watching this project, and the readme of this repo is in English, ~~and I'm too lazy to write Chinese translation~~.

@mingkuang-Chuyu There are many articles saying "Dism++ is open-source", but in spite of it isn't, The Chuyu-Team say _"开源是一种美德，也是一种实力的象征"_ on the homepage, I think you are enjoying and benefiting for the misunderstanding.

**Comment by mingkuang-Chuyu** [comment]
I have repeatedly pointed out that Dism++ is not open source, but others ignore me. I still take it out of context. What can I do?

**Comment by mingkuang-Chuyu** [comment]
另外 网站也是明确说了 
开源是一种美德，也是一种实力的象征，查看初雨团队的开源项目点我。
请注意是 `查看初雨团队的开源项目点我`，不是  `查看Dism++源代码 点我`？

我们只开源基础类库，不会开源程序本身。开源程序本身是等着让别人直接来复制粘贴吗？

**Comment by mercury233** [comment]
So why not you change it to _"开源是一种美德，也是一种实力的象征，虽然Dism++程序本身不开源，但我们开源了一些Dism++使用的类库，查看初雨团队的开源项目点我"_

**Comment by purerosefallen** [comment]
So what's the license of Dism++?

**Comment by MouriNaruto** [comment]
@purerosefallen Dism++ has a license agreement for the proprietary part. But the open source part uses the MIT license in most cases.

**Comment by mercury233** [comment]
那你就继续享受别人的误解吧，反正国产软件圈多你一个不多

**Comment by mingkuang-Chuyu** [comment]
我已经多次说明了  Dism++不是开源的，问题是那些小编又不是我能控制的。在你说提出这个问题的那时，我又来群里发布了 群公告，来周知下，一些转载人士的误解。

他们转载的人  一看到 一个初雨团队的开源项目就以为开源了Dism++好不好？

难道我特意声明（Dism++本身不开源） 这样就破坏网站的整体美感，另外难道加了别人就不会误解了？

你把人想的太简单了，Dism++里面多少功能都有警告信息，有多少人看了？

好了 网站就不会改的，不过我可以在自动更新里 特意 强调下 Dism++本身就不开源的。

**Comment by mingkuang-Chuyu** [comment]
另外我保证  每期自动更新 的内容里 最后 第二行 都是这句话。

**Comment by mercury233** [comment]
愿意四处解释，就是不愿意在官网写明，你这思路我还是不太理解……

_不过反正不关我事，我选择了不同意Dism++使用协议_

_国内做软件不易，加油吧_

**Comment by mingkuang-Chuyu** [comment]
我不是已经明确说了，官网 放着太长了，1 行可以放下的事情 非要变成 2行。

破坏了美感，明明一句简短明了的话 却要被误解。我说，腾讯、微软什么的网站上也是这样的，要不你也去反馈下，网站上却写着微软开源，为什么Windows OS不开源，为什么Office不开源。

为什么别人这样写 你就不会误解、我这样写 就让你们误解了？

另外 你事情也搞明白一点、Dism++官网浏览量大  还是 Dism++自动升级量大？

Dism++官网 一天 就  6000左右的量。

Dism++自动升级  一天可是有 数万！我放弃了一个小的量、选择一个更大的量。不是更好的可以达到告知真相的目的？

**Comment by MouriNaruto** [comment]
@mercury233 我觉得你的脑回路有问题
“开源是一种美德，也是一种实力的象征，查看初雨团队的开源项目点我。”

看看清楚 “查看初雨团队的开源项目”，这只是指查看团队的开源项目
毛利

**Comment by MouriNaruto** [comment]
@mercury233 

我觉得你的脑回路有问题
“开源是一种美德，也是一种实力的象征，查看初雨团队的开源项目点我。”
看看清楚 “查看初雨团队的开源项目”，这只是指查看团队的开源项目，你的理解能力难道就那么差吗？

还有初雨团队并不是公司，只是几个人合作开发。而且因为Dism++还要贴钱。
@mingkuang-Chuyu 每年倒贴好几万用在维护 Dism++ 上面，如果不说你也是不知道的。
团队的其他成员并没有因为从团队赚到一分钱，我曾经告诉我的亲戚我参与了Dism++的开发，然后立马被问赚了多少，当我说并没赚到一分钱的时候他们还在笑我。（当然我也是有收获的，因为 @mingkuang-Chuyu 指导我学会了如何使用 C/C++ 进行项目开发 ）

因为曾经 @mingkuang-Chuyu  接受捐赠后碰到了捐助者装大爷颐指气使的遭遇，于是一直都没有尝试盈利，现在即使开放捐赠其实如果不乐意也是可以退款的。当然为了能够坚持自己的看法，就至今为止而言这是值得的。（其实我自己的那些开源项目也是这样的，不主动找人直接（捐赠、收费等）或间接（广告、推广、捆绑等）要钱（虽然和Dism++一样也开放了捐赠通道，但也是愿者上钩系列），可以想更新就更新（我曾经有拖更一年的记录），想加什么就加什么（有的时候发布新版本只是重构并没有新功能也没有修复任何Bug），只要自己开心就好）

毛利

**Comment by mercury233** [comment]
@MouriNaruto 
我的脑回路确实达不到误导了别人还反过来指责别人理解能力差的水平

以“Dism++ 开源”为关键词搜索，非常多的结果信誓旦旦的说Dism++是开源的，其中不乏知名网站。从这些渠道来的用户到官网一看确实写了团队支持开源，自然就相信了这个谣言

当然你不可能控制别人对你的项目的描述，但在自己官网上，不去澄清反而以美感为由去误导，我是觉得这个思路很神奇

另外你后面说的话是不是想说，
> 因此， @mingkuang-Chuyu 追求虚荣是合理的

**Comment by yfdyh000** [comment]
虽然语句本身没问题，但`Dism++可以说是一个Dism的GUI版，……`的下一句接`开源是一种美德，也是一种实力的象征`有误导性，而且它是`关于 Dism++`章节的一部分。
将`开源是一种美德，也是一种实力的象征`放到页脚的`关于初雨团队`更合理，普通用户不需要了解。
或者哪怕`开源是一种美德，也是一种实力的象征，查看初雨团队的相关开源项目。`

**Comment by MouriNaruto** [comment]
@mercury233 并不是，你的理解能力又有问题了

我的意思是“我们不欠你们的”

**Comment by MouriNaruto** [comment]
@yfdyh000 

嗯，建议我觉得很不错，但如果能提出让大家更加轻松的了解我们自己的开源项目就更好了。

毕竟开源的部分是 Dism++ 重要的组成部分。然后下面说部分也许能满足看这个 issue 的读者的典故。

关于完全开源的建议，我和 @mingkuang-Chuyu （鸭子）讨论过很多次。只是碍于国内的对待开源项目的现状还是很不合适的。

很久之前，希望能造福众人的鸭子对 Dism++ 前身的前身进行了完全开源，结果被一家商业性质的 Windows PE 制作公司（如果没记错，是“电脑店”）去掉了版权并改了名字就商用了。于是愤怒的鸭子就改名为 Dism管理器 并从此开始闭源发布。

在 Dism++ 开发早期，我那时刚刚被鸭子拉入初雨团队。作为开源爱好者的我和鸭子提到了 Dism++ 完全开源的建议。鸭子当时立马把我怼了回去，然后 Dism管理器 群里的一个元老级粉丝跟我说了上面的典故。那时我再也不和鸭子说开源的事情了，毕竟鸭子受到的伤害实在太大。

随着时间的流逝，鸭子觉得开源部分工具库且核心闭源可以造福众人且保护自己的成果不被肆意践踏。于是依次开源了 VC-LTL（原 Dism++ 专用魔改版 VCRT，也是 Dism++ 保持小巧的主要原因）、这个仓库（清理规则、多语言翻译、文档、网站等）和 CPPHelper（Dism++ 的工具库）。开源部分个人觉得占了Dism++ 总体实现的至少70%。当然，这也带来了不少好处，譬如多语言翻译和规则越来越完善好用。

Dism++ 现在闭源的部分主要是本体、青蛙插件（清除账户密码、春哥附体绕过系统检查获取最高权限、Host修改等各种实用功能）和 NCleaner（一些在特定环境下效果拔群的清理项的实现）。青蛙插件和 NCleaner 由于和 Dism++ 紧密结合，所以青蛙（ @FogDai ，青蛙插件的创造者）和我（NCleaner 的创造者）为了防止别人轻松的逆向 Dism++ 本体导致再次悲剧，于是如果 Dism++ 本体不开源的话，这些东西是不存在开源这个说法的。

希望以上内容对你有帮助。

毛利

**Comment by yfdyh000** [comment]
对于`但如果能提出让大家更加轻松的了解我们自己的开源项目就更好了`，可以在边角弄一个大大的图标按钮（链接），比如右上角或左右侧边，会比文字更醒目。
例如 View on GitHub (https://i.stack.imgur.com/JP89T.png) 的风格，写“查看我们开源的组件”或其他措辞。

**Comment by MouriNaruto** [comment]
@yfdyh000 
Dism++ 的官网的确需要修改，虽然 Dism++ 的官网是开源的，但由于网站是鸭子做的，于是我并不知道该怎么生成 Dism++ 的官网（Dism++ 官网在多语言方面貌似有生成器，但对于主要研究如何清理更多系统无用文件的我并不大清楚），所以只能希望鸭子看到你的建议后能够去改善了

其实我比较担心的是，写的再详细也没法避免出现这个 issue 的情况。
我自己也有自己的开源项目，自己在文档对最低要求明明规定的是 Vista / Server 2008；但其他下载站照样标最低 Windows 7 / Server 2008 R2 （表示强烈的怨念）……

**Comment by yfdyh000** [comment]
把位置改掉就能很大程度避免，目前语句位置是接上一句的，有明显（不一定有意）的暗示。

系统支持方面，Vista可能有点罕为人知了，网站为通用、易懂写7也没什么，可能字段都没有Vista。

**Comment by mingkuang-Chuyu** [comment]
网上百度到的就一定是对的吗？Dism++明确写了支持Vista，有多少下载网站没写Dism++ 支持Vista？

另外我也说了，在自动更新的提示信息里添加了声明，昨天就已经添加好了。你大可以去触发升级试试。

而且网站浏览的人本身就少，而放自动更新可以覆盖几乎都所有用户。

最后为什么我要去承担别人的误解？为什么我要去在意别人的看法？我怎么开心我怎么来。我只负责告知义务。

**Comment by optomux** [comment]
What is so magical in Dism++ that is need to be closed source? :)))

**Comment by MouriNaruto** [comment]
@optomux Dism++ is a partial open source project. The open source part is on GitHub. So it is not funny. We can't open source all parts because we don't want to see some one remake a commercial implementation with only changing the project name.
Dism++ is based on CBS Interfaces so Dism++ can support from Vista to 10 with the same binary files. If we use DismAPI or DismCore, we need to prepare three versions of ADK DISM itself.（6.1 6.3 10.0）
You may see Dism++ exports some API with DismAPI style because we want to follow the DISM style for reserving more information in the future.

We love creating open source projects but we should protect ourselves.

I am one of Dism++ developers. I love open source. Dism++ is the only project I participated which is not fully open source. 

Mouri.

**Comment by optomux** [comment]
Not sure I can trust this project without seeing source code. Commercial argument is weak because they can already use NSudo etc.

**Comment by MouriNaruto** [comment]
@optomux 

> Commercial argument is weak because they can already use NSudo etc.

Dism++ is not created by me, I am only a developer. I can't make a decision without permission.
Thank you very much because you can mention the NSudo, the project created by me. I think you know I love creating open source projects.
I don't care about someone uses the projects created by me in the commercial projects if they can mentioned they use it in their projects.
In several years ago, I created the NSudo project and push the source code on GitHub. My friend, the creator of Dism++ and his friends think it's not wise to make the NSudo project open source, they also think they can implement the alternative of the NSudo project in several hours. But he thinks it's good to have a open source project like NSudo today, and he finally came out of the shadow of being plagiarized by others. (Some one remake a commercial implementation with only changing the project name is a real thing that ever happened, and the victim is the creator of Dism++.)

Mouri

**Comment by optomux** [comment]
Where is header for dismcore.dll or CbsHost.dll??

**Comment by MouriNaruto** [comment]
@optomux Disassembler can help you.

**Comment by verdy-p** [comment]
Sorry to disturb you, but your discussion in "French" here is full of non-sense, visibly none of you correctly understand French and it's only possible to read it VERY superficially, trying to guess what it means.
May be French is too difficult for you, but at least you should make efforts to use English first.
Visibly all the above was *automatically* converted from Chinese to English (with some level of unreliability of meaning), and then recoverted automatically from English to French (adding even more level on reliability).
The result is almost unreadable full on non-sense or even many contradictions ! You even double-translate what should be untranslatable (e.g. people name...).
Basic grammatical structure (subject+verb+complement in French like in English, but the typical order or groups is Article+Noun+Adjective most often in French while it is Article+Adjective+Noun in English) is completely lost. Even the boundary between sentences is lost, and sentences are mixed...
Negation is also broken (works different ly in French than in English).
French (like also Italian or Spanish) also uses less adverbs than Chinese or even English, because it uses a rich set of time, gender and number indicators (if it was in German, you would also find grammatical cases and conjunctions would be replaced in many places by agglutination).

**Comment by optomux** [comment]
@MouriNaruto Since it operates through registry it will be easy to reverse engineer. Is sad that we have to do this..

**Comment by MouriNaruto** [comment]
@optomux We don't operates through registry directly because we use Microsoft's interface. In order to respect the Microsoft's original implementations.
So I suggest you to reverse Microsoft's CBS(cbscore.dll) and CSI(wcp.dll) implementations.

Mouri.

**Comment by MouriNaruto** [comment]
@verdy-p  I can talk to others only with Chinese and English.

**Comment by verdy-p** [comment]
@MouriNaruto: pourtant tu es le seul ci-dessus à écrire correctement en français avec des phrases correctement construites et ayant du sens. Le reste au dessus est un complet non-sens qui aurait mieux fait d'être en chinois ou en anglais.
Merci de ne pas utiliser les traducteurs automatiques du chinois vers le français, car ils font des double traductions via l'anglais et c'est encore plus illisible (alors qu'on peut encore deviner le sens d'un anglais partiellement incorrect, c'est impossible après une double traduction vers le français via l'anglais automatique).

On écrit directement soit en chinois (et les traductions vers l'anglais sont "lisibles"), soit en anglais et on a des traductions à peu près correctes vers le chinois et vers le français ou vers pas mal d'autres langues latines et germaniques.

D'ailleurs c'est ce que je reproche à bon nombre de produits chinois, dont les "notices" d'utilisation "en français" sont totalement illisibles voire carrément fausses: les chinois (ab)usent trop des outils de traduction automatique et gagneraient à déjà améliorer et corriger les version anglaises pour qu'elles soient au moins non ambiguës et lisibles (pas besoin du niveau littérature): au besoin se faire aider pour faire relire avec des utilisateurs parfaitement bilingues (voyez du côté de Hong Kong ou Singapour) afin ensuite de pouvoir fournir d'autres langues.

Et surtout n'oubliez pas de fournir la source originale des traductions, pour qu'ensuite on puisse trouver les erreurs de traduction et lever les ambiguïtés nombreuses (notamment à cause de la réutilisation des termes dans des sens différents, et qui se traduisent donc pas du tout en mot en mot en cas de retraduction).

Sinon je suggère à Chuyu Team de poster en chinois et proposer en même temps un aperçu à peu près en anglais (même s'il y a encore des approximations), mais d'éviter toute autre langue si Chuyu Team ne maitrise pas suffisamment l'anglais (ce qui est visiblement le cas). Chuyu Team devrait donc chercher à compléter son équipe par un vrai locuteur en anglais pour faire relire ses infos et superviser ce forum et les réponses apportées : ci-dessus on a un parfait exemple d'incompréhension mutuelle qui donne un "qui proquo" où personne en fait ne se comprend et chacun argumente de façon approximative et dans une langue qu'aucun ne maîtrise assez (sauf toi @MouriNaruto et moi..).

D'une façon générale si on ne maîtrise pas une langue, on ne doit pas essayer de l'imiter, il vaut mieux parler dans sa propre langue et laisser ensuite les autres la comprendre, et leur laisser le choix des outils de traduction automatiques (pour comparer les résultats) ou pour demander de l'aide: il est toujours plus beaucoup facile (pour un humain) de *lire* une langue étrangère que de *l'écrire* (ou la parler) et on évite ensuite des "qui propos" inattendus, on peut les expliquer, et chacun peut alors rester maître de ce qu'il a réellement voulu dire. Si on n'arrive pas à comprendre, on peut demander une reformulation plus simple, mais on n'interprète pas totalement au hasard (comme le font encore tous les traducteurs automatiques).

**Comment by MouriNaruto** [comment]
Archived by #719.
