### ISSUE TITLE
Mark updates permanent after cleaning up replaced WinSxS assemblies in Windows 7

### ISSUE THREAD

**Issue by iamaHUN** [Chuyu-Team/Dism-Multi-language#611]
After running a clean up in the SxS folder, DISM++ should mark the affected updates as permanent somehow.

The problem is that the updates are still removable, this makes the system unable to boot after removing them. Reinstalling these updates in offline mode can be a solution but it would be better if they couldn't be removed easily.

For example I did a clean up after installing the latest monthly update and I was wondering what happens if I uninstall it. After that the system was unable to boot because hal.dll was missing.

**Comment by verdy-p** [comment]
I agree, even if WinSxS is cleaned up from old versions, the repository still contains a trace of older version which may be reinstalled when installing a later update based on it to replace your current version: windows Update will bne able reinstall these old versions temporarily only to make a cache from which differential updates based on them can be applied: not all updates are based on the same branch, sometimes new versions are rebased from an older version and there are no updates published on a dead-end recent version which got only temporary support.
Making changes permanent would prohibit reverting the version you use to an older base from which you will be able to update all the rest, you'll remain in the dead end, and the only way to escape it would then be to reinstall the system completely.
Basically what DISM++ (and DISM) does is only to remove the old version kept on cache even if they are not used (but that can still be restored if needed): when doing that it just clears this cache but the older versions are still restorable from Windows Update if a new update need them in order to be applied.

The same is true about drivers in Windows (at least those downloaded from Winwos Updates, the other driers loaded from OEMs are not tracked this way, notably display drivers, and HD audio drivers, and some SCSI/SAS/SATA/RAID/AHCI accelerated drivers, or some flash memory reader drivers, plus some drivers needed for codecs used by webcams using proprietary "raw" formats or allowing you to control some capture settings on the device).

Generally the drivers coming from Windows Update are only drivers with certified WHQL quality, but not all WHQL drivers are available from it. Windows Update only stores basic drivers that do not always contain all the features supported by the OEM, but only the basic required components (but these drivers from Windows Update also frequently avoid adding unnecessary bloatwares that many OEM driver distribution add to their own installers and not needed for proper Windows working).

Windows also keeps a record of old drivers if ever you want to revert to a base version, the base version should only be WHQL ones. But some drivers loaded from Windows Update or even built in the windows distribution do not even work at all (e.g. nVidia display drivers: bad assumption made by Microsoft which removed components that are still necessary: at each installation of a Windows 10 new image I need to reuse the nVidia GeForce Experience tool to load a working driver, because Windows removes the only working one and replaces it by a very old one that does not even start, fails at boot and forces Widnwos to use legacy SVGA software emulation, using incorrect native display resolution; it's a case where keeping the old driver on the system is completlely useless as those coming from the Windows distribution have never worked correctly in any version; this is very intrigating because the newer version form nVidia itself is WHQL certified, but the certification of the version in Windows Update is completely wrong, it is not compatible except a few very old nVidia display cards, and the same is true about Realtek HD Audio drivers with no sound at all after Windows installation, even if Windows installed its own drivers for the recognized hardware, but not the correct ones: the windows Update repositiry has numerous bugs and contain bad data, not even matching the info within the catalog built in the WHQL driver: Microsoft rebuilt incomplete packages, forgetting necessary components!).

Beware about what happens after each installation a Windows 10 image: generally you need to reinstall many things that have disappeared and that the update removed silently to replace them by old non working versions, and the "migration" process forgets many checks. Microsoft considers that display drivers are not "essential" drivers and that it is fine to update even if your system after the update only support SVGA resolution and software emulation and no 2D/3D acceleration, no OpenGL acceleration, no OpenCL/CUDA support, no support for various color formats for videos; as well it considers that sound is not essential, Microsoft just wants you to be able to boot successfully, and display something on the desktop, it does not care at all about performance...

As well Microsofts Windows Update frequently remove all third party cloud storage drivers, that you need to reinstall and reconnect to your account (it only supports OneDrive and enables it by default even if you don't want it!)

**Comment by MouriNaruto** [comment]
Make update packages permanent in environment which is earlier than Windows 8.1 will cause some problems.

PS: In Windows 10, you may need to reinstall your OS in some scenario if you force enable the ResetBase option to make the update packages perminent.
