### ISSUE TITLE
Dism++ is busy

### ISSUE THREAD

**Issue by raphson93** [Chuyu-Team/Dism-Multi-language#613]
Hi, I was trying to remove the provisioned appx but it keep saying "Dism++ is busy because other programs are running. Please try again later."
Restart PC few times and it still showed the same err.

**Comment by verdy-p** [comment]
Some provisioned AppX cannot in fact be safely removed from Windows 10, trying to remove them will cause the Explorer to crash or no longer working (notably those related to Cortana, which require much more complex removal procedures).

I don't think Dism++ is safe to use to remove these provisioned apps. There are other tools on the Internet explianing how to do that (used for example to create a custom install image for deplyment, notably in professional installations, or when using Sysprep): this does not just requires removing the appX but also change various registry entries to unlink them completely from core Windows components (notably the File Explorer, or from Internet Explorer and Edge).
Those you can safely remove are bloatwares/adwares (such as games, or MS Office Trial, or simple URL links with icons added to the Start menu).
LiveDrive is a bit more complicate to remove: you need to remove the backup and synchronization options set by default in the Security Center. And you may need to remove the approval of some "confidentiality" features (this is easy to do in versions of Windows for the European Union where Windows will not restrict you, because Microsoft must comply to the mandatory European RGPD).
Beware also of some other custom apps you may have added and that add connections to other provisioned Windows AppX, if they are installed (beware notably about Facebook which is very intrusive!)
