### ISSUE TITLE
Enable scrolling during installation of Windows Updates

### ISSUE THREAD

**Issue by demovirus** [Chuyu-Team/Dism-Multi-language#631]
On machines where last updates were installed long time ago we see many found updates in correspondent section of dism++. And there is a vertical scroll bar.
But when I press Install Updates I can't use this scrollbar and see status of updates that not fit to the screen size. Please add ability to scroll update list during installation. You may need to run installation in different thread for it.
Sorry for screen, it's not mine. Just for understanding.
![dism2](https://user-images.githubusercontent.com/25708906/53692186-055b0b00-3dad-11e9-94ce-d71477d77393.jpg)

**Comment by verdy-p** [comment]
This is not just occuring while installing updates, but also for Disk cleanup action, or for settings Startup options, the Toolkit, the System optimizer, selecting/adding/removing Drivers, Windows Updates, and other Deply Features, or when mounting/dismounting an image, or when performing backups/restores :

As long as Dism is busy working (because you pressed one of the buttons at the bottom of the main panel), all the scrollbars, buttons and other UI options in the main pane are blocked (from any input: mouse buttons or wheel, keyboard, touch events, accessibility inputs).

This is not a problem of screen refreshing, because resizing the window works and correct redraws the missing parts, and columns sizes are adjusted accordingly. As well the main menu at top is not blocked, as well as the system menu and window control buttons (maximize, minimize, restore, close, move, resize). As well the display reacts correctly to changes in display settings (change of resolution, change of system colors...), and Dism also accepts having its window moved to another desktop or to a screen with different resolution/colorts.

Note: if you have mounted several images (the live image and another), you can still click on the blue square at to view its state and perform selection there and even scroll it. What is blocked is only the set of checkboxes in the main list, the selector in the left-side panel and the buttons at bottom, which are all linked to the windows image currently being serviced.

What would be needed here is to not block all UI elements, only block the UI elements that may have an action or would change the current selection in the currently mounted Windows image on which Dism is performing an action: the currently selected items must keep their current status. 

You're right, there's no reason to block the scrollbar while Dism++ is working. We should be able to scroll down/up the list to show the current progress, without having to wait for completion.

**Comment by mingkuang-Chuyu** [comment]
This is caused by my laziness and may improve the experience in the future.

Thuanks

**Comment by DooML** [comment]
+1!

**Comment by demovirus** [comment]
Why closed? Did you fix it?

**Comment by MouriNaruto** [comment]
Won't fix temporarily because of design.

**Comment by verdy-p** [comment]
in fact you have closed ALL submitted bugs massively without discrimination.
When I saw that, the only reply is that this software is no longer supported at all (and the closure of the website that has been completely erased with 404 page not found is another sign that the initial authors have renounced, or they have abused us with malwares in one version, or that the software had copyright violations, and their site was forced shutdown by some authority).
Also the site affirmed the software was "open source" when in fact only some parts (some third party libraries and the translations) were open. All the rest was proprietary (and now very suspect).
Closing all bugs also shows that even this repository is now completely unmanaged, or managed by a new person that wants to clear the whole history.
Now we have two distinct "justifications" given : "by design", and "for political reasons", with no more details. I think the Chinese authors are in severe judicial troubles (possibly linked to the situation in Hong Kong and the severe censure by China behind now its numeric "Great Wall", or by the political conflict with US and the closure of several important internet links, and blocking of many major internet service providers, including those legally established in Hong Kong).

**Comment by verdy-p** [comment]
I do think that "mingkuang-Chuyu" is now completely inactive in this project (or can no longer work on it). I even wonder if he still has any control of its source code (or if its computing environment was not simply seized, just like the website was erased).
MouriNaruto is new here, and is closing everything. I think he may be a member of a Chinese authority, disguised under a fake Japanese avatar (but GitHuc also reveals that he's located in China too), and for now he did not provide any real work on the project (or he stole the control from the initial author, via his third party plugin for the NTDLL/Mint libary)

**Comment by MouriNaruto** [comment]
@verdy-p

If you can't read Chinese, please use translator.

> closing everything
I chose close GitHub issue service of this project before I closed all issues, but mingkuang told me not to do that. So I had closed all issues because lots of issues have a long long history. Finally, I reopen most issues again. Because I have followed https://github.com/Chuyu-Team/Dism-Multi-language/pull/706. 

> MouriNaruto is new here.
I am the *one of three initial developers* of Dism++, I used most of my time in Dism++ source code which is closed source and the MDL forum.
My first contribution of Dism++ is the hot backup support which is based on Volume Shadow Service, the implementation had been written in July 31th, 2014.
I had started to use and love C++ because of development of Dism++.

> for now he did not provide any real work on the project
I am the author of NCleaner.dll in Dism++, and do some work in CBSHost.dll and Dism++*.exe. Also I am the author of the first Dism++ post in PCBeta forum and MDL forum. I am the first localization translator of Dism++.

This is my first named contribution.
![image](https://user-images.githubusercontent.com/10867563/63939733-88c69200-ca9a-11e9-8e14-97190bb5db53.png)

This is my first contribution, and it still used in today's Dism++.
![image](https://user-images.githubusercontent.com/10867563/63940021-30dc5b00-ca9b-11e9-9233-3161ecdfcdf7.png)

You can find some foundation implementations of NCleaner.dll in NSudo(https://github.com/M2Team/NSudo).

If you are a human instead of an animal, you will know my mean.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@verdy-p

Any reply?

**Comment by verdy-p** [comment]
Le jeu. 29 août 2019 à 14:30, Kenji Mouri <notifications@github.com> a
écrit :
>
> If you are a human instead of an animal, you will know my mean.

But why are you closing massively all past issues like a bot using a
script, not like a human ?
Is the initial author now completely out of the project and was forced to
abandon it? Why is the website shutdown/erased ?

And yes you are very new compared to all others that have contributed since
longer and for many more things that the very few you made. For now the
project is left unmanaged but it seems you got a way to take the lead on it
and decide to stop everything of the past.

I don't know what happened for the initial main author, but visibly it's no
longer here and probably has even lost the control of the project, and
possibly even the source of the proprietary part; may be it was hacked
externally and there's no way to recover cleanly: that's the downside of
proprietary projects managed by a very small team without any form of
delegation and cooperation. If he had troubles maintaining it alone, he
should have saved his work by making it really open sourced (not just
translations and some side tools that he used for that software).

> Any reply?

Also why do you hurry in expecting a fast reply to your message in less
than a few hours, when you took several days to see my comment. I was just
notified by GitHub today and only just saw your comment a few minutes ago.
I'm not always connected to the Internet, or there are other things to do
on the web and other mails to handle in the history. I cannot react
immediately and don't have the time to be always on, I have also a life
outside.

It's now a fact that the main software has a severe problem, and the main
site is also in severe troubles. But nothing has been posted to explain
what is happening and what is the future of this project.

**Comment by MouriNaruto** [comment]
@verdy-p

作为一个中国人，既然被你搞的发飙，我就来点中文。

> Why is the website shutdown/erased ?

因为减少因国家四部委检查的麻烦，反正九月网站应该会开了。

> I don't know what happened for the initial main author.

鸭子现在忙于他开的基础库项目，所以 Dism++ 处于非活跃开发阶段。

> it's no longer here and probably has even lost the control of the project

Dism++ 始终由鸭子领导，无可争议。

> For now the project is left unmanaged but it seems you got a way to take the lead on it
and decide to stop everything of the past.

笑死我了，我从来都无意成为 Dism++ 的领航者，因为这个坑的前身的前身是青蛙挖的，然后后来她为了学业把项目交给鸭子（当时是男友，现在是丈夫），而鸭子是大家都知道的这个坑的缔造者。

> And yes you are very new compared to all others that have contributed since longer.

呵呵，我也是第一次被人这样侮辱。如果光看然并卵的 Dism++ GitHub 仓库贡献，那么在这个仓库贡献基本没有而只在闭源部分有贡献的青蛙，是不是她要做点调整，会被你这样的玩意喷的更惨？

Dism++ 始终最核心的还是闭源代码，而能维护闭源部分的现在也就只有鸭子、青蛙和毛利（也就是我）

倒是你要是真的对青蛙这么做了，不仅仅是你逃不过我的手掌，也逃不过青蛙的丈夫也就是鸭子的算账。

> that's the downside of proprietary projects managed by a very small team without any form of
delegation and cooperation

我们使用微软的代码托管服务进行协作，所以别小看初雨团队。

> If he had troubles maintaining it alone, he should have saved his work by making it really open sourced (not just translations and some side tools that he used for that software).

Dism++ 因为其前身的前身开源后被某商业组织直接商用，除了改名外没有任何修改。所以鸭子从此以后一直闭源。后来开源了一些基础库，反正你们也不关心。

> But nothing has been posted to explain what is happening and what is the future of this project.

因为你不是中国人，你不用 QQ，自然是不知道 Dism++ 最新情况的。
Dism++ 社区主要以 QQ 群为主，反正 Dism++ 的界面上你能找到加群链接，找不到证明你有视觉障碍。

> I cannot react immediately and don't have the time to be always on, I have also a life outside.

我才不管你有没有空，因为你触犯了我的底线。

## 注释

鸭子和青蛙是我相当尊敬的朋友兼前辈，你这么说直接破了我的底线，所以我就是要用中文，就是要让你难受，哈哈哈哈。
我真的想直接开喷或者是直接封禁，但是鸭子希望我成为一个有风度的人，所以还是用中文表达不快吧。
当然，不是中国人，才不知道鸭子就是冥王（mingkuang），我发出了不吉波普那样的狂笑。

**Comment by MouriNaruto** [comment]
I have banned verdy-p because his words insults me.
