### ISSUE TITLE
反馈一个BUG，Win10 2004 19041.207新问题

### ISSUE THREAD

**Issue by 84741595** [Chuyu-Team/Dism-Multi-language#792]
Win10 2004 19041.207自带的记事本不再集成在系统，需要在”可选功能“自己添加，但用DISM++“空间回收"后, 会把添加的记事本清理掉。

**Comment by MrEagle123** [comment]
I confirm this bug. After applying option "Disk Clean-up"->"Replaced WinSxS Assemblies", Windows\system32\notepad.exe is deleted.

我確認這一點。應用選項“磁盤清理”->“替換的WinSxS程序集”後，Windows\system32\notepad.exe被刪除。

**Comment by shulzzzrulezzz** [comment]
I also have this bug, but I have it even when using the standard dism utility from microsoft, it also disappears notepad.exe

**Comment by Lukiya** [comment]
Same issue here.
BTW, Accessories->Paint broken too.

**Comment by azhuge233** [comment]
Windows 10 2004 19041.58 still has this bug.
It also causes Windows Mail and Chinese IME problems.

- The Mail app can't fetch new mails, or add/delete mail accounts.
- Chinese Windows IME doesn’t show a preview box under any input line. According to [this post](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1848284), this is because cleaning WinSxS will delete windows experience pack so the new IME comes with 2004 won't work properly.

It might also clean the Windows monthly update, every time I finish cleaning WinSxS and after a reboot, I hit check update in Settings, the monthly update appears again and starts installing.

**Comment by mingkuang-Chuyu** [comment]
https://github.com/Chuyu-Team/Dism-Multi-language/issues/816

同一个原因导致
